### ISSUE TITLE
gax-java(windows): Flaky FlowControllerTest.testNumberOfBytesOutOfBoundaryWontDeadlock

### ISSUE THREAD

**Issue by burkedavison** [googleapis/gapic-generator-java#1286]
Build failure is flaky and so far only common for Windows.

Java 8 succeeded. [Java 11](https://github.com/googleapis/gapic-generator-java/actions/runs/4039697629/jobs/6944670805) and [Java 17](https://github.com/googleapis/gapic-generator-java/actions/runs/4039697629/jobs/6944670892) failed. Both passed on re-run.
```
Error:  com.google.api.gax.batching.FlowControllerTest.testNumberOfBytesOutOfBoundaryWontDeadlock  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError: expected:<WAITING> but was:<RUNNABLE>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.google.api.gax.batching.FlowControllerTest.testNumberOfBytesOutOfBoundaryWontDeadlock(FlowControllerTest.java:611)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

**Comment by burkedavison** [comment]
[Flaked](https://github.com/googleapis/gapic-generator-java/actions/runs/4070386542/jobs/7011178551) last night.

**Comment by burkedavison** [comment]
[Flaked](https://github.com/googleapis/gapic-generator-java/actions/runs/4119904794/jobs/7114088262) last night on Java 11

**Comment by burkedavison** [comment]
Flaked last night on [Java 11](https://github.com/googleapis/gapic-generator-java/actions/runs/4179720242/jobs/7239981414) and [Java 17](https://github.com/googleapis/gapic-generator-java/actions/runs/4179720242/jobs/7239981558)

**Comment by burkedavison** [comment]
[Nightly flake](https://github.com/googleapis/gapic-generator-java/actions/runs/4199816834/jobs/7285157164) on Java 17

**Comment by burkedavison** [comment]
[Flake](https://github.com/googleapis/gapic-generator-java/actions/runs/4299107315/jobs/7493971162) on Java 17

**Comment by alicejli** [comment]
Nightly build for Java 17 on windows-2022 failed. #1630
