### ISSUE TITLE
gapic: DefaultValueComposer generates invalid default values

### ISSUE THREAD

**Issue by burkedavison** [googleapis/gapic-generator-java#1371]
DefaultValueComposer generates an invalid default value:
https://github.com/googleapis/gapic-generator-java/blob/main/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java

Discovered by @lqiu96 while playing around with Operations in Java-Redis: 
https://cloud.google.com/java/docs/reference/google-cloud-redis/latest/com.google.cloud.redis.v1.CloudRedisClient#com_google_cloud_redis_v1_CloudRedisClient_createInstanceAsync_com_google_cloud_redis_v1_LocationName_java_lang_String_com_google_cloud_redis_v1_Instance_

```
## Using the default sample:
package com.google.cloud.redis.v1;
 
import java.io.IOException;
import java.util.concurrent.ExecutionException;
 
public class Main {
  public static void main(String[] args) {
    try (CloudRedisClient cloudRedisClient = CloudRedisClient.create()) {
      LocationName parent = LocationName.of("[redacted]", "us-central1");
      String instanceId = "instanceId902024336";
      Instance instance = Instance.newBuilder().build();
      Instance response = cloudRedisClient.createInstanceAsync(parent, instanceId, instance).get();
    } catch (IOException e) {
      throw new RuntimeException(e);
    } catch (ExecutionException e) {
      throw new RuntimeException(e);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
}
 
Output:
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
	at com.google.cloud.redis.v1.Main.main(Main.java:16)
Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:125)
	at com.google.cloud.redis.v1.Main.main(Main.java:12)
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:98)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Instance ID must be 1 to 40 characters and use lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number.
	at io.grpc.Status.asRuntimeException(Status.java:539)
	... 17 more
 
Process finished with exit code 1
```

**Comment by blakeli0** [comment]
I see this as part of the SnippetGen Phase 2, as there is no way for the generator to know the backend requirements for all the APIs.

**Comment by lqiu96** [comment]
> I see this as part of the SnippetGen Phase 2, as there is no way for the generator to know the backend requirements for all the APIs.

Sounds good! I think there was part 2 of the issue with the sample which may or may not be tracked with Phase 2. Throwing it out there to see if this is also in scope:

Resolving the instanceId to have all lowercase then leads to this issue:
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid value for 'instance.tier': 'TIER_UNSPECIFIED'.
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Invalid value for 'instance.tier': 'TIER_UNSPECIFIED'.
```

which was resolved with something like:
```
public class Main {
  public static void main(String[] args) {
    try (CloudRedisClient cloudRedisClient = CloudRedisClient.create()) {
      LocationName parent = LocationName.of("lawrence-test-project-2", "us-central1");
      String instanceId = "instanceid902024336";
      Instance instance = Instance.newBuilder().setTier(Instance.Tier.BASIC).setMemorySizeGb(1).build();  // <-Changes in this line
      Instance response = cloudRedisClient.createInstanceAsync(parent, instanceId, instance).get();
    } catch (IOException e) {
      throw new RuntimeException(e);
    } catch (ExecutionException e) {
      throw new RuntimeException(e);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
}
```

Granted this also related to knowing the backend requirements. It would be nice for the samples to include the minimum required values for a given RPC.

**Comment by blakeli0** [comment]
> It would be nice for the samples to include the minimum required parameters for a given RPC.

Yes this is exactly what Phase 2 would do, all input of the samples will be provided.

**Comment by lqiu96** [comment]
> > It would be nice for the samples to include the minimum required parameters for a given RPC.
> 
> Yes this is exactly what Phase 2 would do, all input of the samples will be provided.

Gotcha, that's awesome! If that's being tracked with Phase 2, I'm not sure if we need to track it here (or we can keep it) -- Up to you all 😄

**Comment by burkedavison** [comment]
Closing this issue, as it has a known solution in Phase 2 with separate priority.
