### ISSUE TITLE
Unable to build googleapis library with local gapic-generator-java

### ISSUE THREAD

**Issue by lqiu96** [googleapis/gapic-generator-java#1499]
Error Message for building local library:
```
Starting local Bazel server and connecting to it...
DEBUG: Rule 'com_googleapis_gapic_generator_go' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "d9fa55ef3bc14e1c3c15870ef1080a29e6af2b996e37a1d7043f35a61aa1e869"
DEBUG: Repository com_googleapis_gapic_generator_go instantiated at:
  /Users/lawrenceqiu/IdeaProjects/googleapis/WORKSPACE:168:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository com_google_api_gax_java instantiated at:
  /Users/lawrenceqiu/IdeaProjects/googleapis/WORKSPACE:289:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'com_google_api_gax_java':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip] to /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/com_google_api_gax_java/temp11953110264635311995/v2.15.4-SNAPSHOT.zip: GET returned 404 Not Found
ERROR: /Users/lawrenceqiu/IdeaProjects/googleapis/WORKSPACE:289:13: fetching http_archive rule //external:com_google_api_gax_java: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip] to /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/com_google_api_gax_java/temp11953110264635311995/v2.15.4-SNAPSHOT.zip: GET returned 404 Not Found
ERROR: Error computing the main repository mapping: no such package '@com_google_api_gax_java//': java.io.IOException: Error downloading [https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip] to /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/com_google_api_gax_java/temp11953110264635311995/v2.15.4-SNAPSHOT.zip: GET returned 404 Not Found
```

**Comment by blakeli0** [comment]
Do you still have the issue if [this line](https://github.com/googleapis/googleapis/blob/650f7cd5b652b902b8189a657736dc56655ecf61/WORKSPACE#L278) is commented out?

**Comment by lqiu96** [comment]
> Do you still have the issue if [this line](https://github.com/googleapis/googleapis/blob/650f7cd5b652b902b8189a657736dc56655ecf61/WORKSPACE#L278) is commented out?

Error:
```
Starting local Bazel server and connecting to it...
DEBUG: Rule 'com_googleapis_gapic_generator_go' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "d9fa55ef3bc14e1c3c15870ef1080a29e6af2b996e37a1d7043f35a61aa1e869"
DEBUG: Repository com_googleapis_gapic_generator_go instantiated at:
  /Users/lawrenceqiu/IdeaProjects/googleapis/WORKSPACE:168:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository com_google_api_gax_java instantiated at:
  /Users/lawrenceqiu/IdeaProjects/googleapis/WORKSPACE:288:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'com_google_api_gax_java':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip] to /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/com_google_api_gax_java/temp1286758972211290600/v2.15.4-SNAPSHOT.zip: GET returned 404 Not Found
ERROR: /Users/lawrenceqiu/IdeaProjects/googleapis/WORKSPACE:288:13: fetching http_archive rule //external:com_google_api_gax_java: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip] to /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/com_google_api_gax_java/temp1286758972211290600/v2.15.4-SNAPSHOT.zip: GET returned 404 Not Found
ERROR: Error computing the main repository mapping: no such package '@com_google_api_gax_java//': java.io.IOException: Error downloading [https://github.com/googleapis/gapic-generator-java/archive/v2.15.4-SNAPSHOT.zip] to /private/var/tmp/_bazel_lawrenceqiu/e651f412bb9d781d683087b8b31b9bbe/external/com_google_api_gax_java/temp1286758972211290600/v2.15.4-SNAPSHOT.zip: GET returned 404 Not Found
```

I updated to this:
```
_gapic_generator_java_version = "2.15.4-SNAPSHOT"

maven_install(
    artifacts = [
        "com.google.api:gapic-generator-java:" + _gapic_generator_java_version,
    ],
    #Update this False for local development
    fail_on_missing_checksum = False,
    repositories = [
        "m2Local",
        "https://repo.maven.apache.org/maven2/",
    ]
)

local_repository(
    name = "gapic_generator_java",
    path = "/Users/lawrenceqiu/IdeaProjects/gapic-generator-java",
)

# gax-java is part of gapic-generator-java repository
local_repository(
    name = "com_google_api_gax_java",
    path = "/Users/lawrenceqiu/IdeaProjects/gapic-generator-java/gax-java",
)
```
and this works find to build

**Comment by lqiu96** [comment]
@blakeli0 

This changed worked for me (not sure if there is a better way):
```
_gapic_generator_java_version = "2.15.4-SNAPSHOT"

maven_install(
    artifacts = [
        "com.google.api:gapic-generator-java:" + _gapic_generator_java_version,
    ],
    #Update this False for local development
    fail_on_missing_checksum = False,
    repositories = [
        "m2Local",
        "https://repo.maven.apache.org/maven2/",
    ]
)

local_repository(
    name = "gapic_generator_java",
    path = "/Users/lawrenceqiu/IdeaProjects/gapic-generator-java",
)

# gax-java is part of gapic-generator-java repository
local_repository(
    name = "com_google_api_gax_java",
    path = "/Users/lawrenceqiu/IdeaProjects/gapic-generator-java/gax-java",
)
```
