### ISSUE TITLE
NPE for LRO's with response type "google.protobuf.Empty"

### ISSUE THREAD

**Issue by aohren** [googleapis/gapic-generator-java#441]
GAPIC generation on the `googleads/v5` protos fails with a NPE when encountering an LRO with `response_type: "google.protobuf.Empty"`.  

Specifically, when GAPIC generation gets to [googleads/v5/services/batch_job_service.proto:RunBatchJob](https://github.com/googleapis/googleapis/blob/00bbad4dfd6633cf4b5f9596c1f93b756bb5c776/google/ads/googleads/v5/services/batch_job_service.proto#L81), the following exception is thrown:

```
Exception in thread "main" java.lang.NullPointerException: LRO response message Empty not found on method RunBatchJob
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.api.generator.gapic.protoparser.Parser.parseLro(Parser.java:384)
	at com.google.api.generator.gapic.protoparser.Parser.parseMethods(Parser.java:331)
	at com.google.api.generator.gapic.protoparser.Parser.lambda$parseService$0(Parser.java:196)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.api.generator.gapic.protoparser.Parser.parseService(Parser.java:199)
	at com.google.api.generator.gapic.protoparser.Parser.parseServices(Parser.java:132)
	at com.google.api.generator.gapic.protoparser.Parser.parse(Parser.java:103)
	at com.google.api.generator.gapic.Generator.generateGapic(Generator.java:29)
	at com.google.api.generator.Main.main(Main.java:35)
```

**Comment by aohren** [comment]
Adding a reference to `empty_proto` in the `proto_library_with_info` deps fixed the NPE. 

```
proto_library_with_info(
    name = "googleads_proto_with_info",
    deps = [
        ":googleads_proto",
        "@com_google_protobuf//:empty_proto",
    ],
)
```
