### ISSUE TITLE
cannot use "case" as a field name

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator-java#956]
If a field is named `case` in the protos, the generator fails with the following exception:

```
Exception in thread "main" com.google.api.generator.engine.ast.IdentifierNode$InvalidIdentifierException: Name case cannot be a keyword.
	at com.google.api.generator.engine.ast.IdentifierNode$Builder.build(IdentifierNode.java:99)
	at com.google.api.generator.engine.ast.IdentifierNode$Builder.buildVariableIdentifier(IdentifierNode.java:63)
	at com.google.api.generator.engine.ast.Variable$Builder.build(Variable.java:46)
	at com.google.api.generator.gapic.composer.common.AbstractServiceClientClassComposer.lambda$createMethodVariants$6(AbstractServiceClientClassComposer.java:668)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.api.generator.gapic.composer.common.AbstractServiceClientClassComposer.createMethodVariants(AbstractServiceClientClassComposer.java:671)
	at com.google.api.generator.gapic.composer.common.AbstractServiceClientClassComposer.createServiceMethods(AbstractServiceClientClassComposer.java:578)
	at com.google.api.generator.gapic.composer.common.AbstractServiceClientClassComposer.createClassMethods(AbstractServiceClientClassComposer.java:216)
	at com.google.api.generator.gapic.composer.common.AbstractServiceClientClassComposer.generate(AbstractServiceClientClassComposer.java:150)
	at com.google.api.generator.gapic.composer.Composer.lambda$generateClientSettingsClasses$3(Composer.java:134)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at com.google.api.generator.gapic.composer.Composer.generateClientSettingsClasses(Composer.java:122)
	at com.google.api.generator.gapic.composer.Composer.generateServiceClasses(Composer.java:58)
	at com.google.api.generator.gapic.composer.Composer.composeServiceClasses(Composer.java:45)
	at com.google.api.generator.gapic.Generator.generateGapic(Generator.java:30)
	at com.google.api.generator.Main.main(Main.java:28)
--java_gapic_out: protoc-gen-java_gapic: Plugin failed with status code 1.
```

[AIP-140](https://google.aip.dev/140) suggests that the APIs _should not_ use possible keywords in names but does not forbid it, and this specific API won't be able to rename it because it's already public.

**Comment by suztomo** [comment]
Memo:

"case" is in the `KEYWORDS` in https://github.com/googleapis/gapic-generator-java/blob/422882b3da787d34385a0df640e8a40dc0627442/src/main/java/com/google/api/generator/engine/lexicon/Keyword.java#L50 that's why IdentifierNode class throws the exception.

**Comment by suztomo** [comment]
@alexander-fenster (Aside from deciding what to do with gapic-generator-java) Do you know who introduced the "case" field. Is it possible to provide the feedback to the person (and approvers) that you are suffering the "case" field conflicting with Java's keywords?

**Comment by alexander-fenster** [comment]
@suztomo I added a comment in the internal issue 221506923 because the offending proto is not yet public.

**Comment by yihanzhen** [comment]
I had a similar issue when I tried to generate Java libraries for artifactregistry API where a resource name has the collection name "package" in it ([proto link](https://github.com/googleapis/googleapis/blob/master/google/devtools/artifactregistry/v1beta2/package.proto#L31-L45)). The resource should have be annotated with `google.api.resource` but doing so would cause Java generation to fail.
